// tslint:disable
/**
 * Infura User Database
 * Web team\'s interface to our Infura\'s user-master dynamo tables
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: avery.max@consensys.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const foo = 'baz';
